CREATE TABLE USER (ID VARCHAR2(25) NOT NULL, PASSWORD VARCHAR2(15) NOT NULL, FIRST_NAME VARCHAR2(20) NOT NULL, LAST_NAME VARCHAR2(20), CONTACT VARCHAR2(15) NOT NULL, EMAIL VARCHAR2(25) NOT NULL);

ALTER TABLE USER ADD CONSTRAINT USER_ID_PK PRIMARY KEY (ID);

CREATE TABLE ADDRESS (ID NUMBER(10), LANE1 VARCHAR2(25) NOT NULL, LANE2 VARCHAR2(25), CITY VARCHAR2(25) NOT NULL, STATE VARCHAR2(25) NOT NULL, COUNTRY VARCHAR2(25) NOT NULL);